#!/usr/bin/env bash
#
# Post-installation Configuration Scripts
#
# Common Debian based host tasks
# - Install Docker packages
# - Install rancher server
# - Install nfs

DOCKER_VERSION=17.09
__RANCHER_DOMAIN__=localhost:8080

install_docker () {
  apt-get install -y curl
  curl https://releases.rancher.com/install-docker/$DOCKER_VERSION.sh | sh
  cat > /etc/docker/daemon.json << EOF
{
  "dns": ["8.8.8.8", "8.8.4.4"]
}
EOF
  service docker restart
}

install_rancher () {
	docker run -d --restart=unless-stopped --name=rancher-server -p 8080:8080 rancher/server
	
	apt-get install -y jq

	# Get project ID
	PROJECT_ID=$(curl -s http://$__RANCHER_DOMAIN__/v1/projects | jq -r ".data[0].id")

	# Create registration token
	curl -s -X POST http://$__RANCHER_DOMAIN__/v1/registrationtokens?projectId=$PROJECT_ID

	# Get registration token
	TOKEN=`curl -s http://$__RANCHER_DOMAIN__/v1/registrationtokens?projectId=$PROJECT_ID | jq -r '.data[0].token'`

	# Get docker image name
	RANCHER_AGENT_CMD=`curl -s http://$__RANCHER_DOMAIN__/v1/registrationtokens?projectId=$PROJECT_ID | jq -r '.data[0].command'`

	# Start up the beast
	$RANCHER_AGENT_CMD

}

install_nfs () {
	apt-get install -y nfs-kernel-server
	mkdir /var/nfs
	chown nobody:nogroup /var/nfs
	cat '/var/nfs    *(rw,sync,no_subtree_check,no_root_squash)' >> /etc/exports
	systemctl restart nfs-kernel-server
}

main () {
	install_docker
	install_rancher
	touch deb_docker_done
}


main
