#!/usr/bin/env bash
#
# Post-installation Configuration Scripts
#
# Common Debian based host tasks
# - Install base packages
# - Set cool root prompt


do_upgrade () {
  apt-get --assume-yes update
  apt-get --assume-yes upgrade
  apt-get --assume-yes dist-upgrade
}


install_base_packages () {
  apt-get --assume-yes install sudo tmux bash-completion ca-certificates
  apt-get --assume-yes install git lm-sensors nano
}

set_prompt () {
  cat >> /root/.bash_rc <<EOF
PS1="\n\
┌ \e[0;91m\${?}\e[0m ─ \e[0;31m\t\e[0m ─ \e[0;32m\u\e[0m@\e[0;94m\h\e[0m\n\
│\e[0;33m\${PWD}\e[0m\n\
└ "

PS2="\
└ "

alias rm='rm -I'
alias l='ls -la --color=always -p --time-style="+%Y:%m:%d-%H%M%S%-:::z"'
alias upd='apt-get update'
alias upg='apt-get upgrade && apt-get dist-upgrade'
alias upda='upd && upg'
alias ..='cd ..'
EOF
}


main () {
	do_upgrade
	install_base_packages
	set_prompt
	touch deb_host_done
}


main
